---
# yamllint disable rule:line-length
name: 'Modify external repo to checkout from'
description: "Modify external repo to check out from"
inputs:
  repo:
    description: "The name of the GitHub repo"
    required: true
  default_branch:
    description: "The default branch to check out if no overrides"
    required: false
    default: 'master'
runs:
  using: "composite"
  steps:
    - name: Check out jbaublitz/${{ inputs.repo }}
      if: github.event_name == 'pull_request'
      id: jbaublitz
      continue-on-error: true
      uses: actions/checkout@v5
      with:
        repository: jbaublitz/${{ inputs.repo }}
        path: jbaublitz
        ref: ${{ github.head_ref }}
        persist-credentials: false
    - name: Check out mulkieran/${{ inputs.repo }}
      if: github.event_name == 'pull_request'
      id: mulkieran
      continue-on-error: true
      uses: actions/checkout@v5
      with:
        repository: mulkieran/${{ inputs.repo }}
        path: mulkieran
        ref: ${{ github.head_ref }}
        persist-credentials: false
    - name: Check if both checkouts succeeded
      if: github.event_name == 'pull_request' && steps.jbaublitz.outcome == 'success' && steps.mulkieran.outcome == 'success'
      shell: bash
      run: |
        echo "Branch conflict!"
        exit 1
    - name: Conditionally make jbaublitz checkout branch the chosen one
      if: github.event_name == 'pull_request' && steps.jbaublitz.outcome == 'success'
      shell: bash
      run: mv jbaublitz ${{ inputs.repo }}
    - name: Conditionally make mulkieran checkout branch the chosen one
      if: github.event_name == 'pull_request' && steps.mulkieran.outcome == 'success'
      shell: bash
      run: mv mulkieran ${{ inputs.repo }}
    - name: Check out stratis-storage repo if no alternative branch was checked out
      if: github.event_name != 'pull_request' || (github.event_name == 'pull_request' && steps.mulkieran.outcome == 'failure' && steps.jbaublitz.outcome == 'failure')
      uses: actions/checkout@v5
      with:
        repository: stratis-storage/${{ inputs.repo }}
        path: ${{ inputs.repo }}
        ref: ${{ inputs.default_branch }}
        persist-credentials: false
