---
name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  checks:
    uses: $/.github/workflows/reusable_general.yml
    with:
      fedora-container-image-number: 43  # CURRENT DEVELOPMENT ENVIRONMENT
